language: python
os: linux
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: bionic
    - python: 3.8
      dist: bionic
    - python: 3.9
      dist: bionic

install:
    - "pip install pipenv pytest-cov codecov"
    - "pipenv install --dev"
    - "python -m nltk.downloader punkt stopwords"

script:
    - "python -m pytest --cov=ruts --cov-fail-under=70"

after_success:
    - codecov